name: Deploy to Firebase Hosting and Functions - Main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Set Environment
        run: echo "ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Build Project
        run: npm run build

      - name: Generate firebase.json
        run: node predeploy.js
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DENEME_REFLECT_FIREBASE }}
          projectId: deneme-reflect-firebase
          channelId: main

      - name: Deploy Firebase Functions
        run: npx firebase-tools deploy --only functions:ssrMain --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
