name: Deploy to Firebase Hosting and Functions - Live

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build Release
        run: npm run build

      - name: Deploy Firebase Functions (Live)
        run: npx firebase-tools deploy --only functions:ssrreflect --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Firebase Hosting (Live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DENEME_REFLECT_FIREBASE }}
          projectId: deneme-reflect-firebase
          channelId: live
          target: live
