name: Deploy to Firebase Hosting and Functions - Test

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build Test
        run: npm run build

      - name: Deploy Firebase Hosting (Test)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DENEME_REFLECT_FIREBASE }}
          projectId: deneme-reflect-firebase
          channelId: test
          target: test

      - name: Deploy Firebase Functions (Test)
        run: npx firebase-tools deploy --only functions:ssrMain --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ENVIRONMENT: development
